// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcuhth--6S9evhbDcgncywqAPvb3Ee4g',
    appId: '1:34168810038:android:d61c9bee262fe7b4508697',
    messagingSenderId: '34168810038',
    projectId: 'chat-app-31f8b',
    storageBucket: 'chat-app-31f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASCKwsROQqWoSVxAXuFQY6gpE6EQ530Fo',
    appId: '1:34168810038:ios:700a934c2db7b2f9508697',
    messagingSenderId: '34168810038',
    projectId: 'chat-app-31f8b',
    storageBucket: 'chat-app-31f8b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsKqieT8bTP_uxEw-F89pRpYgLPi8DINc',
    appId: '1:34168810038:web:5cd658514f2f5a35508697',
    messagingSenderId: '34168810038',
    projectId: 'chat-app-31f8b',
    authDomain: 'chat-app-31f8b.firebaseapp.com',
    storageBucket: 'chat-app-31f8b.appspot.com',
  );

}